package notastruct.primitive

@unsigned class u2
@unsigned class u3
@unsigned class u4
@unsigned class u5
@unsigned class u6
@unsigned class u7
@unsigned class u8
@unsigned class u9
@unsigned class u10
@unsigned class u11
@unsigned class u12
@unsigned class u13
@unsigned class u14
@unsigned class u15
@unsigned class u16
@unsigned class u17
@unsigned class u18
@unsigned class u19
@unsigned class u20
@unsigned class u21
@unsigned class u22
@unsigned class u23
@unsigned class u24
@unsigned class u25
@unsigned class u26
@unsigned class u27
@unsigned class u28
@unsigned class u29
@unsigned class u30
@unsigned class u31
@unsigned class u32
@unsigned class u33
@unsigned class u34
@unsigned class u35
@unsigned class u36
@unsigned class u37
@unsigned class u38
@unsigned class u39
@unsigned class u40
@unsigned class u41
@unsigned class u42
@unsigned class u43
@unsigned class u44
@unsigned class u45
@unsigned class u46
@unsigned class u47
@unsigned class u48
@unsigned class u49
@unsigned class u50
@unsigned class u51
@unsigned class u52
@unsigned class u53
@unsigned class u54
@unsigned class u55
@unsigned class u56
@unsigned class u57
@unsigned class u58
@unsigned class u59
@unsigned class u60
@unsigned class u61
@unsigned class u62
@unsigned class u63
