package notastruct.primitive

import notastruct.primitive.annotation.signed

@signed class s2
@signed class s3
@signed class s4
@signed class s5
@signed class s6
@signed class s7
@signed class s8
@signed class s9
@signed class s10
@signed class s11
@signed class s12
@signed class s13
@signed class s14
@signed class s15
@signed class s16
@signed class s17
@signed class s18
@signed class s19
@signed class s20
@signed class s21
@signed class s22
@signed class s23
@signed class s24
@signed class s25
@signed class s26
@signed class s27
@signed class s28
@signed class s29
@signed class s30
@signed class s31
@signed class s32
@signed class s33
@signed class s34
@signed class s35
@signed class s36
@signed class s37
@signed class s38
@signed class s39
@signed class s40
@signed class s41
@signed class s42
@signed class s43
@signed class s44
@signed class s45
@signed class s46
@signed class s47
@signed class s48
@signed class s49
@signed class s50
@signed class s51
@signed class s52
@signed class s53
@signed class s54
@signed class s55
@signed class s56
@signed class s57
@signed class s58
@signed class s59
@signed class s60
@signed class s61
@signed class s62
@signed class s63
@signed class s64
